### ISSUE TITLE
As expected it gives a warning message this year

### ISSUE THREAD

**Issue by cmfrtblynmb728** [tyleransom/econJobMarket#1]
Hello

I found your code while trying to manage my applications. The idea sounds terrific, unfortunately I can't write such a code on my own. I tried the code this year and I get the following error:

`Error in if (file.exists(file) == FALSE) if (!missing(asText) && asText ==  : 
  argument is of length zero`

I tried to find where the problem was, I found that line 47 creates the issue.  This particular line in question: 

`employers[i] <- xmlValue(getNodeSet(htmlParse(as.character(temp2[3])), "//span")[[1]])`

I wish I could debug it further but I don't understand that particular line. From that particular line it can't create EJM files. 

Just wanted to inform you

Thanks

**Comment by tyleransom** [comment]
@cmfrtblynmb728 Thanks for bringing this to my attention. This issue is probably due to EJM tweaking their site (they don't have an API so the information is all manually captured).

Just to confirm, does the code still work for JOE? That's where the lion's share of the listings are, so it's most important that JOE is working.

I don't have a ton of time to devote to this right now, but I'll see what I can do.

**Comment by tyleransom** [comment]
@cmfrtblynmb728 I just pushed a commit that should solve the issue. Can you give it a try and let me know if it works? (note that the EJM scraping script takes much longer than the JOE one)

**Comment by cmfrtblynmb728** [comment]
Hello 

Sorry for the late response. I have not tried this one JOE. I mostly needed it for EJM since they have a very archaic search and sort system. I will give it a try and let you know of the results

Thank you!

**Comment by cmfrtblynmb728** [comment]
Ok, I just checked it. 

I think the last line gives an error on my computer, but I changed it. It said: 

`Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '../Output/All_EJM_jobs_2017-11-18_processed.csv': No such file or directory`

I just typed `write.csv(EJM, file = "processed.csv")` and it gave me the file. 

But there is one more issue it seems. The code does not fetch the name of the institution correctly. The first and the second column are the same, they are the names of the positions.  For example it says "Assistant professor"  for both the employer and the position. 

Here is the screenshot of it: 

https://imgur.com/a/YGeLs

**Comment by cmfrtblynmb728** [comment]
Thanks by the way :) 👍

**Comment by tyleransom** [comment]
OK, I just fixed that. Try downloading the most recent version. (The change I made was on line 47 ... `htmlParse(as.character(temp2[3]))` became `htmlParse(as.character(temp2[4]))`.

Please close this issue if everything looks good.

**Comment by cmfrtblynmb728** [comment]
Thank you!
